apiVersion: v2
name: repertoire
description: Répertoire Téléphonique - CRUD API + Frontend
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - repertoire
  - crud
  - mongodb
maintainers:
  - name: Repertoire Team
