{{- if and .Values.ingress.enabled .Values.ingress.tls }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "repertoire.fullname" . }}-tls
  labels:
    {{- include "repertoire.labels" . | nindent 4 }}
spec:
  secretName: {{ (index .Values.ingress.tls 0).secretName }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    {{- range (index .Values.ingress.tls 0).hosts }}
    - {{ . }}
    {{- end }}
{{- end }}
