{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "repertoire.fullname" . }}-frontend
  labels:
    {{- include "repertoire.frontend.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    {{- range .Values.ingress.hosts }}
    - match: Host(`{{ .host }}`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{ include "repertoire.fullname" $ }}-frontend
          port: {{ $.Values.frontend.service.port }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    secretName: {{ (index .Values.ingress.tls 0).secretName }}
  {{- end }}
{{- end }}
